# Generated by Django 5.0 on 2024-01-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='size',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
