# Generated by Django 5.0 on 2024-01-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
